export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const FORWARD_USER_FROM_LOGIN = 'FORWARD_USER_FROM_LOGIN';
export const LOGOUT_USER = 'LOGOUT_USER';
