export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const FORWARD_USER_FROM_LOGIN = 'FORWARD_USER_FROM_LOGIN';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SHOW_USER_FORM = 'SHOW_USER_FORM';
export const RESET_USER_FORM = 'RESET_USER_FORM';
export const USER_REGISTRATION_START = 'USER_REGISTRATION_START';
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAIL = 'USER_REGISTRATION_FAIL';

export const SHOW_CATEGORY_FORM = 'SHOW_CATEGORY_FORM';
export const RESET_CATEGORY_FORM = 'RESET_CATEGORY_FORM';
export const CATEGORY_CREATION_START = 'CATEGORY_CREATION_START';
export const CATEGORY_CREATION_SUCCESS = 'CATEGORY_CREATION_SUCCESS';
export const CATEGORY_CREATION_FAIL = 'CATEGORY_CREATION_FAIL';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_FILTERED_USERS = 'FETCH_FILTERED_USERS';
export const CHANGE_USERS_PAGE = 'CHANGE_USERS_PAGE';
export const BLOCK_UNBLOCK_USER = 'BLOCK_UNBLOCK_USER';

export const TOGGLE_DROPDOWN = 'TOGGLE_DROPDOWN';

export const FETCH_REPORTS_START = 'FETCH_REPORTS_START';
export const FETCH_REPORTS_SUCCESS = 'FETCH_REPORTS_SUCCESS';
export const FETCH_REPORTS_FAIL = 'FETCH_REPORTS_FAIL';
export const REMOVE_REPORT_SUCCESS = 'REMOVE_REPORT_SUCCESS';
export const DELETE_ANSWER_SUCCESS = 'DELETE_ANSWER_SUCCESS';
export const CHANGE_ANSWERS_PAGE = 'CHANGE_ANSWERS_PAGE';

export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';

export const FETCH_QUESTIONS_START = 'FETCH_QUESTIONS_START';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FAIL = 'FETCH_QUESTIONS_FAIL';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_FAIL = 'FETCH_SEARCH_FAIL';
export const POST_QUESTION_SUCCESS = 'POST_QUESTION_SUCCESS';
export const POST_QUESTION_FAIL = 'FETCH_QUESTIONS_FAIL';

export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const UPDATE_PASSWORD_START = 'UPDATE_PASSWORD_START';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL';

export const FETCH_CONTACT_START = 'FETCH_CONTACT_START';
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS';
export const FETCH_CONTACT_FAIL = 'FETCH_CONTACT_FAIL';
export const UPDATE_CONTACT_START = 'UPDATE_CONTACT_START';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_FAIL = 'UPDATE_CONTACT_FAIL';

export const FETCH_STUDENT_START = 'FETCH_STUDENT_START';
export const FETCH_STUDENT_SUCCESS = 'FETCH_STUDENT_SUCCESS';
export const FETCH_STUDENT_FAIL = 'FETCH_STUDENT_FAIL';
export const UPDATE_STUDENT_START = 'UPDATE_STUDENT_START';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_FAIL = 'UPDATE_STUDENT_FAIL';

export const FETCH_FACULTY_START = 'FETCH_FACULTY_START';
export const FETCH_FACULTY_SUCCESS = 'FETCH_FACULTY_SUCCESS';
export const FETCH_FACULTY_FAIL = 'FETCH_FACULTY_FAIL';
export const UPDATE_FACULTY_START = 'UPDATE_FACULTY_START';
export const UPDATE_FACULTY_SUCCESS = 'UPDATE_FACULTY_SUCCESS';
export const UPDATE_FACULTY_FAIL = 'UPDATE_FACULTY_FAIL';
