export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const FORWARD_USER_FROM_LOGIN = 'FORWARD_USER_FROM_LOGIN';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SHOW_USER_FORM = 'SHOW_USER_FORM';
export const RESET_USER_FORM = 'RESET_USER_FORM';
export const USER_REGISTRATION_START = 'USER_REGISTRATION_START';
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAIL = 'USER_REGISTRATION_FAIL';
